DROP TABLE PARTIDO;
DROP TABLE COMPETICION;
DROP TABLE JUGADOR;
DROP TABLE EQUIPO;
DROP TABLE ESTADIO;

 
CREATE TABLE ESTADIO(
   	ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
   	CAPACIDAD NUMBER NOT NULL,
    REGION NUMBER,
    CONSTRAINT ESTADIO_PK PRIMARY KEY("ID"),
    CONSTRAINT ESTADIO_REGION_FK FOREIGN KEY(REGION) REFERENCES REGIONS(REGION_ID)
   ) TABLESPACE "USERS";

CREATE TABLE EQUIPO ( 
 "ID" NUMBER NOT NULL ENABLE, 
 "NOMBRE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
 "PRESUPUESTO" NUMBER, 
 "REGION" NUMBER, 
  CONSTRAINT "EQUIPO_PK" PRIMARY KEY ("ID"), 
  CONSTRAINT "EQUIPO_REGION_FK" FOREIGN KEY ("REGION")
   REFERENCES "HR"."REGIONS" ("REGION_ID") ENABLE
   )TABLESPACE "USERS";  
  
  CREATE TABLE JUGADOR ( 
  	NOMBRE VARCHAR2(50 BYTE) NOT NULL, 
	APELLIDOS VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	ID NUMBER NOT NULL ENABLE, 
	FECHANACIMIENTO DATE, 
	PAIS CHAR(2 BYTE), 
	EQUIPO NUMBER, 
	ACTIVO CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
	FOTO VARCHAR(100),
	CONSTRAINT JUGADOR_PK PRIMARY KEY (ID), 
	CONSTRAINT JUGADOR_PAIS_FK FOREIGN KEY (PAIS) REFERENCES COUNTRIES(COUNTRY_ID), 
	CONSTRAINT JUGADOR_EQUIPO_FK FOREIGN KEY (EQUIPO) REFERENCES EQUIPO(ID)
   ) TABLESPACE "USERS" ;

  CREATE TABLE COMPETICION (
   	ID NUMBER NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    INICIO DATE NOT NULL,
    FIN DATE NOT NULL,
    REGION NUMBER NOT NULL,
    CONSTRAINT COMPETICION_PK PRIMARY KEY(ID),
	CONSTRAINT COMPETICION_REGION_FK FOREIGN KEY(REGION) REFERENCES REGIONS(REGION_ID)
   ) TABLESPACE "USERS";
      
   CREATE TABLE PARTIDO(
   	ID NUMBER NOT NULL,
    "LOCAL" NUMBER NOT NULL,
    VISITANTE NUMBER NOT NULL,
    ESTADIO NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    COMPETICION NUMBER,
    CONSTRAINT PARTIDO_PK PRIMARY KEY("ID"),
    CONSTRAINT PARTIDO_LOCAL_FK FOREIGN KEY("LOCAL") REFERENCES EQUIPO(ID),
    CONSTRAINT PARTIDO_VISITANTE_FK FOREIGN KEY(VISITANTE) REFERENCES EQUIPO(ID),
    CONSTRAINT PARTIDO_ESTADIO_FK FOREIGN KEY(ESTADIO) REFERENCES ESTADIO(ID),
    CONSTRAINT PARTIDO_COMPETICION_FK FOREIGN KEY(COMPETICION) REFERENCES COMPETICION(ID)
   ) TABLESPACE "USERS";
      
         
DROP SEQUENCE EQUIPO_SEQUENCE;
DROP SEQUENCE JUGADOR_SEQUENCE;
DROP SEQUENCE ESTADIO_SEQUENCE;
DROP SEQUENCE PARTIDO_SEQUENCE;
DROP SEQUENCE COMPETICION_SEQUENCE;   

CREATE SEQUENCE  EQUIPO_SEQUENCE  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE  JUGADOR_SEQUENCE  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE  ESTADIO_SEQUENCE  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE  PARTIDO_SEQUENCE  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE  COMPETICION_SEQUENCE  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1;